### ISSUE TITLE
Rewind

### ISSUE THREAD

**Issue by jsr5194** [MaskedFox/learnTheHardWay#10]
https://github.com/MaskedFox/learnTheHardWay/blob/6d61451eb918e15e29a50f84e08417abdbe54e84/learnPython3/ex20.py#L22

I see that you commented above what this does, but can you tell us why it is being used?

**Comment by MaskedFox** [comment]
The rewind function takes one argument(file) and goes back to the beginning of the current line due to to f.seek(0), position zero

**Comment by jsr5194** [comment]
Good. Go ahead and close
