### ISSUE TITLE
the_count list

### ISSUE THREAD

**Issue by jsr5194** [MaskedFox/learnTheHardWay#13]
https://github.com/MaskedFox/learnTheHardWay/blob/c8bc79f72440a05db47ef29944563f298e8ae2d3/learnPython3/ex32.py#L7

So here he has you iterating over each of the elements of a list containing incrementing numbers. While this works, it obviously does not scale well if you wanted to iterate over values from say 0-10000. Can you find another way that you could accomplish the same thing?

**Comment by MaskedFox** [comment]
for i in range(1,6):
    print(i)

**Comment by jsr5194** [comment]
Since the numbers he gave are only 1-5 as opposed to 0-5, this is correct

go ahead and close when you see this
