### ISSUE TITLE
Incrementing Shorthand

### ISSUE THREAD

**Issue by jsr5194** [MaskedFox/learnTheHardWay#14]
https://github.com/MaskedFox/learnTheHardWay/blob/c8bc79f72440a05db47ef29944563f298e8ae2d3/learnPython3/ex33.py#L9

This works, but can you find a more commonly used way of incrementing a variable by an integer?

**Comment by MaskedFox** [comment]
you mean something like i += 1
?

**Comment by jsr5194** [comment]
Exactly. 

This one can close
