### ISSUE TITLE
Format String Printing

### ISSUE THREAD

**Issue by jsr5194** [MaskedFox/learnTheHardWay#15]
https://github.com/MaskedFox/learnTheHardWay/blob/c8bc79f72440a05db47ef29944563f298e8ae2d3/learnPython3/ex34.py#L14

Why did you choose to print out the variables like this? What other ways do you already know about?

**Comment by MaskedFox** [comment]
I think i wanted to play more with "\n"
This is another way i could think of:

print("""
animals[1]
animals[2]
animals[0]
animals[3]
animals[4]
animals[2]
animals[5]
animals[4]
""")

**Comment by jsr5194** [comment]
Are you sure those do the same thing? Did you actually run the second one?

**Comment by MaskedFox** [comment]
Crap, that didnt worked as well as in my head. This would be the right way to do the same:
```
print(f"""
{animals[1]}
{animals[2]}
{animals[0]}
{animals[3]}
{animals[4]}
{animals[2]}
{animals[5]}
{animals[4]}
"""
```

**Comment by MaskedFox** [comment]
besides de two way i have and this one:
```
print(animals[1], animals[2], animals[0], animals[3], animals[4], animals[2], animals[5], animals[4])
```
Is there a better way to print these?

**Comment by jsr5194** [comment]
Really i just wanted you to think about other ways of printing. There are tons of ways to accomplish it. 

for example another way to keep the newlines you had in the first one would be like this:
```
print("{}\n{}\n{}\n".format(animals[0], animals[1], animals[2]))
```
Keep in mind I'm not saying this is the absolute correct way to do it. Just another way to format things

**Comment by jsr5194** [comment]
Go ahead and close when you see this
