### ISSUE TITLE
Cars driven

### ISSUE THREAD

**Issue by Knight-Ops** [MaskedFox/learnTheHardWay#2]
Thought problem : 

If a cars capacity is 4, and it is being driven, can you still carry 4 more passengers? If you cannot does this equation for calculating the average number of passengers per car still hold true?

**Comment by MaskedFox** [comment]
No, it doesnt hold true anymore. Although in a third world country you could probably fit up to 6 =p

**Comment by Knight-Ops** [comment]
What would the new equations be for how many people per car would you use?
