### ISSUE TITLE
Leave Descriptive Comments Rather Than Literal Comments

### ISSUE THREAD

**Issue by jsr5194** [MaskedFox/learnTheHardWay#3]
https://github.com/MaskedFox/learnTheHardWay/blob/20f4572aedaf1edc9ca200e6abe596eb061da992/learnPython3/ex6.py#L4

So, i'm looking at the exercises you pushed a bit ago. In general when you're commenting code the point isn't really to just say what the syntax means (that part is usually self explanatory). The effectiveness of comments really comes when you explain the reason for what you've done. For example:
```
# setting vars with strings  
binary = "binary"  
do_not = "don't "  
```
in this case you're just saying what is done in the step below. A more useful comment here would be to document why you made the choices you did (which i realize in this case were because you were told to do it). For example:
```
# showing how an apostrophe can be used within a string
binary = "binary"
do_not = "don't"
```
gives the reader an indication of what you were trying to do when writing that code, allowing them to better understand what is happening

**Comment by MaskedFox** [comment]
Will do, thanks!
