### ISSUE TITLE
end=" "

### ISSUE THREAD

**Issue by Knight-Ops** [MaskedFox/learnTheHardWay#5]
https://github.com/MaskedFox/learnTheHardWay/blob/65b207a81bf2dbdf91774b8c18074914d460da20/learnPython3/ex7.py#L23

Space in between what? Each letter or the print statement on L#24 and L#25, the explicitness in your comments will help your future self and anyone else looking at your code.

**Comment by MaskedFox** [comment]
You are right, space between the first print and the second print.
